[package]
name = "fet2ods"
version = "0.1.0"
authors = ["vcarceler"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
spsheet = "0.1.0"
